LocationVoiturePhilippeB/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using static System.Net.Mime.MediaTypeNames;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using LocationVoiturePhilippeB.Models;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Contrôleur pour la gestion complète des clients
    /// </summary>
    [Authorize(Roles = "Admin, Client")]
    public class ClientController : Controller
    {
        private IClientRepository _clientRepository;
        private IWebHostEnvironment _hostingEnvironment;
        public ClientController(IClientRepository clientRepository, IWebHostEnvironment webHostEnvironment)
        {
            _clientRepository = clientRepository;
            _hostingEnvironment = webHostEnvironment;
        }
        /// <summary>
        /// Retourne la liste des clients
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Client, Admin")]
        public ViewResult ListeClients()
        {
            return View(_clientRepository.ListeClients);
        }
        /// <summary>
        /// Affichage de la page d'ajout d'un client
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }
        /// <summary>
        /// Affichage de la page de modification d'un client
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Client client = _clientRepository.GetClientById(id);
            return View(client);
        }
        /// <summary>
        /// Méthode d'action qui permet la suppression d'un client de la liste
        /// </summary>
        /// <param name="id"> Correspond au client sélectionné</param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult Supprimer(int id)
        {
            _clientRepository.Supprimer(id);
            return RedirectToAction(nameof(ListeClients));
        }
        /// <summary>
        /// Méthode d'action qui permet l'ajout d'un client dans la liste
        /// - Redirection vers la vue des clients (ListeClients)
        /// - Le code de téléversement sécuritaire est pris d'une démo de Dalicia Bouallouche
        /// - Utilisation de la validation côté serveur 
        /// </summary>
        /// <param name="client"></param>
        /// <returns></returns>
        [HttpPost]
        public RedirectToActionResult AjouterClient(Client client)
        {
            if (client.Photo != null)
            {
                string nomImage = Path.GetFileName(client.Photo.FileName);
                string extensionImage = Path.GetExtension(nomImage);

                var repertoireTeleversements = Path.Combine(_hostingEnvironment.ContentRootPath, "Televersements\\Clients");

                Directory.CreateDirectory(repertoireTeleversements);

                nomImage = Guid.NewGuid().ToString() + extensionImage;

                var cheminImage = Path.Combine(repertoireTeleversements, nomImage);
                client.urlPhoto = cheminImage;


                // Enregistrer l'image sur le disque
                using (var stream = new FileStream(cheminImage, FileMode.Create))
                {
                    client.Photo.CopyTo(stream);
                }
            }
            if (ModelState.IsValid)
            {
                _clientRepository.Ajouter(client);
                return RedirectToAction(nameof(ListeClients));
            }
            
            return RedirectToAction(nameof(Ajouter));
        }
        /// <summary>
        /// Méthode d'action qui permet la modification d'un client dans la liste
        /// - Redirection vers la vue des clients (ListeClients)
        /// - Le code de téléversement sécuritaire est pris d'une démo de Dalicia Bouallouche
        /// - Utilisation de la validation côté serveur 
        /// </summary>
        /// <param name="client"></param>
        /// <returns></returns>
        [HttpPost]
        public RedirectToActionResult ModifierClient(Client client)
        {
            if (client.Photo != null)
            {
                string nomImage = Path.GetFileName(client.Photo.FileName);
                string extensionImage = Path.GetExtension(nomImage);

                var repertoireTeleversements = Path.Combine(_hostingEnvironment.ContentRootPath, "Televersements\\Clients");

                Directory.CreateDirectory(repertoireTeleversements);

                nomImage = Guid.NewGuid().ToString() + extensionImage;

                var cheminImage = Path.Combine(repertoireTeleversements, nomImage);
                client.urlPhoto = cheminImage;


                // Enregistrer l'image sur le disque
                using (var stream = new FileStream(cheminImage, FileMode.Create))
                {
                    client.Photo.CopyTo(stream);
                }
            }
            if (ModelState.IsValid) 
            {
                _clientRepository.Modifier(client);
                return RedirectToAction(nameof(ListeClients));
            }
            
            return RedirectToAction(nameof(Modifier));
        }
       
    }
}

LocationVoiturePhilippeB/Controllers/ErreursController.cs
using LocationVoiturePhilippeB.ViewModels;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Contrôleur qui permet d'afficher les différents messages dans la vue d'erreur personnalisée selon le code de statut
    /// Code tiré de la démo des gestions d'exeptions de Dalicia Bouallouche
    /// </summary>
    public class ErreursController : Controller
    {
        [Route("Erreurs/GererErreur{codeEtat}")]
        public ViewResult GererErreur(int codeEtat)
        {
            ErreurViewModel erreurViewModel = new ErreurViewModel
            {
                CodeErreur = codeEtat,
            };
            if (codeEtat == 404)
            {
                erreurViewModel.ErrorMsg = "Désolé, cette page n'existe pas";
            }

            return View("Erreur", erreurViewModel);
        }

        [Route("Erreurs/GererErreurGlobale")]
        public ViewResult GererErreurGlobale()
        {
            IExceptionHandlerPathFeature exceptionDetails = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            string hostingEnv = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

            ErreurViewModel erreurViewModel = new ErreurViewModel
            {
                CodeErreur = HttpContext.Response.StatusCode,
                ErrorMsg = "Oops, Une erreur s'est produite durant l'exécution de votre requête!",

                CheminException = exceptionDetails.Path,
                MessageException = exceptionDetails.Error.Message,
                TraceException = exceptionDetails.Error.StackTrace,
                ModeDev = hostingEnv == "Development"
            };

            return View("Erreur", erreurViewModel);
        }
    }
}

LocationVoiturePhilippeB/Controllers/LocationController.cs
using LocationVoiturePhilippeB.Models;
using LocationVoiturePhilippeB.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Controlleur pour afficher le viewmodel qui contient les locations
    /// </summary>
    public class LocationController : Controller
    {
        private readonly IPanierRepository _panierRepository;
     
        public LocationController(IPanierRepository panier)
        {
            _panierRepository = panier;
        }

        public ViewResult AfficherLocation()
        {
            LocationViewModel model = new LocationViewModel()
            {
                ListeLocations = _panierRepository.GetLocations(),
                Datedebut = DateTime.Now,
                MontantTotal = _panierRepository.MontantTotalPanier()
            };
            return View(model);
        }
    }
}

LocationVoiturePhilippeB/Controllers/PanierController.cs
using LocationVoiturePhilippeB.Models;
using LocationVoiturePhilippeB.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Contrôlleur qui permet la gestion complète du panier de locations
    /// </summary>
    [Authorize(Roles = "Admin, Client")]
    public class PanierController : Controller
    {
        private readonly IPanierRepository _panierRepository;
        private readonly IVoitureRepository _voitureRepository;
        private IHttpContextAccessor _contextAccessor;

        /// <summary>
        /// Constructeur du controlleur pour créer une session à chaque utilisation du panier
        /// </summary>
        /// <param name="panier"></param>
        /// <param name="voiture"></param>
        /// <param name="contextAccessor"></param>
        public PanierController(IPanierRepository panier, IVoitureRepository voiture, IHttpContextAccessor contextAccessor)
        {
            _panierRepository = panier;
            _voitureRepository = voiture;
            _contextAccessor = contextAccessor;

            var panierSessionId = _contextAccessor.HttpContext.Session.GetString("PanierSessionId");
            if (string.IsNullOrEmpty(panierSessionId))
            {
                panierSessionId = Guid.NewGuid().ToString();
                _contextAccessor.HttpContext.Session.SetString("PanierSessionId", panierSessionId);
            }
            _panierRepository.SetSessionId(panierSessionId);
            ViewBag.PanierSessionId = panierSessionId;
        }
        /// <summary>
        /// Affichage du panier d'achat dans le ViewModel attribué
        /// - Le montant total est calculé avec une requête LINQ du PanierRepository
        /// </summary>
        /// <returns></returns>
        public ViewResult AfficherPanier()
        {
            PanierViewModel model = new PanierViewModel
            {
                ListeVoituresPanier = _panierRepository.VoiturePanier,
                MontantTotal = _panierRepository.MontantTotalPanier()
            };
            return View(model);
        }
        /// <summary>
        /// Méthode d'action qui permet l'ajout d'une voiture dans le panier
        /// - Appelle de la fonction "AjouterAuPanier" du PanierRepository
        /// </summary>
        /// <param name="vehiculeId"> Récupérer automatiquement quand l'utilisateur appuie sur "Ajouter au panier" dans la vue </param>
        /// <returns></returns>
        public RedirectToActionResult AjouterAuPanier(int vehiculeId)
        {
            Voiture voiture = _voitureRepository.GetVoitureById(vehiculeId);

            _panierRepository.AjouterAuPanier(voiture);

            return RedirectToAction(nameof(AfficherPanier));
        }
        /// <summary>
        /// Méthode d'action qui permet la suppression d'une voiture dans le panier
        /// - Appelle de la fonction "SupprimerDuPanier" du PanierRepository
        /// </summary>
        /// <param name="vehiculeId"></param>
        /// <returns></returns>
        public RedirectToActionResult SupprimerDuPanier(int vehiculeId)
        {
            Voiture voiture = _voitureRepository.GetVoitureById(vehiculeId);

            _panierRepository.SupprimerDuPanier(voiture);

            return RedirectToAction(nameof(AfficherPanier));
        }
        /// <summary>
        /// Méthode d'action qui supprime l'entièreté du contenu du panier
        /// </summary>
        /// <returns></returns>
        public RedirectToActionResult ViderPanier()
        {
            _panierRepository.ViderPanier();

            return RedirectToAction(nameof(AfficherPanier));
        }
    }
}

LocationVoiturePhilippeB/Controllers/VoitureController.cs
using LocationVoiturePhilippeB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Controlleur qui permet la gestion complète des voitures 
    /// </summary>
    [Authorize(Roles = "Admin, Client")]
    public class VoitureController : Controller
    {
        private IVoitureRepository _voitureRepository;
        private IWebHostEnvironment _webHostEnvironment;

        public VoitureController(IVoitureRepository voitureRepository, IWebHostEnvironment webHostEnvironment)
        {
            _voitureRepository = voitureRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        /// <summary>
        /// Affichage de la liste des voitures disponibles
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin, Client")]
        public ViewResult ListeVoitures()
        {
            return View(_voitureRepository.ListeVoitures);
        }
        /// <summary>
        /// Affichage de la vue d'ajout d'une voiture
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }
        /// <summary>
        /// Affichage de la vue de modification d'une voiture
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Voiture voiture = _voitureRepository.GetVoitureById(id);
            return View(voiture);
        }
        /// <summary>
        /// Méthode d'action qui permet la suppression d'une voiture dans la base de données
        /// </summary>
        /// <param name="id"> Récupérer automatiquement quand on sélectionne la voiture à supprimer</param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult Supprimer(int id)
        {
            _voitureRepository.Supprimer(id);
            return RedirectToAction(nameof(ListeVoitures));
        }
        /// <summary>
        /// Méthode d'action qui permet l'ajout d'une voiture dans la BD
        /// - Redirection vers la vue des voitures (ListeVoitures)
        /// - Le code de téléversement sécuritaire est pris d'une démo de Dalicia Bouallouche
        /// - Utilisation de la validation côté serveur 
        /// </summary>
        /// <param name="voiture"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public RedirectToActionResult AjouterVoiture(Voiture voiture)
        {
            if (voiture.Image != null)
            {
                string nomImage = Path.GetFileName(voiture.Image.FileName);
                string extensionImage = Path.GetExtension(nomImage);

                var repertoireTeleversements = Path.Combine(_webHostEnvironment.ContentRootPath, "Televersements\\Voitures");

                Directory.CreateDirectory(repertoireTeleversements);

                nomImage = Guid.NewGuid().ToString() + extensionImage;

                var cheminImage = Path.Combine(repertoireTeleversements, nomImage);
                voiture.UrlImage = cheminImage;


                // Enregistrer l'image sur le disque
                using (var stream = new FileStream(cheminImage, FileMode.Create))
                {
                    voiture.Image.CopyTo(stream);
                }
            }
            if (ModelState.IsValid)
            {
                _voitureRepository.Ajouter(voiture);
                return RedirectToAction(nameof(ListeVoitures));
            }
            return RedirectToAction(nameof(Ajouter));
        }
        /// <summary>
        /// Méthode d'action qui permet la modification d'une voiture dans la BD
        /// - Redirection vers la vue des voitures (ListeVoitures)
        /// - Le code de téléversement sécuritaire est pris d'une démo de Dalicia Bouallouche
        /// - Utilisation de la validation côté serveur 
        /// </summary>
        /// <param name="voiture"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public RedirectToActionResult ModifierVoiture(Voiture voiture)
        {
            if (voiture.Image != null)
            {
                string nomImage = Path.GetFileName(voiture.Image.FileName);
                string extensionImage = Path.GetExtension(nomImage);

                var repertoireTeleversements = Path.Combine(_webHostEnvironment.ContentRootPath, "Televersements\\Voitures");

                Directory.CreateDirectory(repertoireTeleversements);

                nomImage = Guid.NewGuid().ToString() + extensionImage;

                var cheminImage = Path.Combine(repertoireTeleversements, nomImage);
                voiture.UrlImage = cheminImage;


                // Enregistrer l'image sur le disque
                using (var stream = new FileStream(cheminImage, FileMode.Create))
                {
                    voiture.Image.CopyTo(stream);
                }
            }
            if (ModelState.IsValid) 
            {
                _voitureRepository.Modifier(voiture);
                return RedirectToAction(nameof(ListeVoitures));
            }
            return RedirectToAction(nameof(Modifier));
        }
    }
}

LocationVoiturePhilippeB/Views/Shared/Erreur.cshtml
@model ErreurViewModel

@{
    ViewData["Titre"] = "Page d'erreur";
}

<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="alert alert-danger text-center">
        <h1>Erreur @Model.CodeErreur</h1>
        <p>Message d'erreur : @Model.ErrorMsg</p>
    </div>
</div>

@if (Model.ModeDev)
{
    <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="alert alert-danger text-center">
            <h5>Exception Path</h5>
            <hr />
            <p>
                @Model.CheminException
            </p>
        </div>
    </div>

    <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="alert alert-danger text-center">
            <h5>Exception message</h5>
            <hr />
            <p>
                @Model.MessageException
            </p>
        </div>
    </div>

    <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="alert alert-danger text-center">
            <h5>Exception Stack Trace</h5>
            <hr />
            <p>
                @Model.TraceException
            </p>
        </div>
    </div>
}

LocationVoiturePhilippeB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-Xvr7+LUDZ2O6T9w+lDgOl8s9OMxIbb5vKv7KB8RtkTGKbi2IKbRSMx9VLfRUTI3tL4+acDbkAowwt9QIa/9aHg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/StyleSheet.css" rel="stylesheet"/>
    <script src="~/jquery/jquery.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-ewfXo9Gq53e1q1+WDTjaHAGZ8UvCWq0eXONhwDuIoaH8xz2r96uoAYaQCm1oQhnBfRXrvJztNXFsTloJfgbL5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
</head>
<body class="bg-light">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<button class="navbar-toggler" data-bs-toggle="collapse" type="button" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="#">
			<img src="/images/logoentreprise.png" width="70" height="40" alt="">
		</a>

		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a asp-action="Index" asp-controller="PagePrincipale" class="nav-link">Accueil</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"> Client</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a asp-action="ListeClients" asp-controller="Client" class="dropdown-item">Liste</a>
						@if (User.IsInRole("Admin")){
                        <a asp-action="Ajouter" asp-controller="Client" class="dropdown-item">Ajouter</a>
                        }
					</div>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"> Voiture</a>
					<div class="dropdown-menu bg-dark">
						<a asp-action="ListeVoitures" asp-controller="Voiture" class="dropdown-item text-white">Liste</a>
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="Ajouter" asp-controller="Voiture" class="dropdown-item text-white">Ajouter</a>
                        }
                    </div>
				</li>
                <li class="nav-item active">
                    <a asp-action="AfficherLocation" asp-controller="Location" class="nav-link">Locations</a>
                </li>
				<li class="nav-item active">
					<a asp-action="AfficherPanier" asp-controller="Panier" class="nav-link">Panier de location</a>
				</li>
			</ul>
            
		</div>
        <div class="ml-auto">
            <partial name="_LoginPartial" />
        </div>
	</nav>
   
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="container-fluid bg-dark text-light py-3 sticky-footer">
    <div class="row">
        <div class="col-md-4 text-center text-md-start">
            <a href="/" class="text-light text-decoration-none">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                    <span class="ms-2">Location'Express</span>
            </a>
        </div>
        <div class="col-md-4 text-center text-md-start">
            <ul class="list-inline">
                <li class="list-inline-item"><a asp-action="Index" asp-controller="PagePrincipale" class="text-light text-decoration-none">Accueil</a></li>
                <li class="list-inline-item"><a asp-action="ListeVoitures" asp-controller="Voiture" class="text-light text-decoration-none">Véhicules</a></li>
                <li class="list-inline-item"><a asp-action="ListeClients" asp-controller="Client" class="text-light text-decoration-none">Clients</a></li>
				<li class="list-inline-item">
					<a href="#" class="text-light text-decoration-none" data-bs-toggle="modal" data-bs-target="#modalApropos">À propos</a>
				</li>
                <li class="list-inline-item"><a href="#" class="text-light text-decoration-none">Contact</a></li>
            </ul>
        </div>
        <div class="col-md-4 text-center text-md-end">
                <span class="text-muted">© 2023 - Tous droits réservés - Location'Express</span>
        </div>
    </div>
</footer>
    <!-- Modal à propos -->
    <div class="modal fade" id="modalApropos" tabindex="-1" aria-labelledby="modalaproposLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modalaproposLabel">À propos de notre entreprise</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
                <p>Notre histoire commence il y a plusieurs années avec un passionné d'automobile, Philippe. Il a partagé une vision commune : créer une entreprise qui se démarque dans l'industrie de la location de voitures en offrant des services de qualité supérieure et une expérience exceptionnelle aux clients. C'est ainsi que Location'Express est né.</p>
                <p>Depuis nos modestes débuts, nous avons parcouru un long chemin pour devenir l'une des principales entreprises de location de voitures de la région. Nous sommes fiers de notre flotte diversifiée de véhicules modernes et bien entretenus, allant des voitures économiques aux véhicules haut de gamme, en passant par les VUS spacieux. Quelle que soit votre préférence, nous avons le véhicule idéal pour vous accompagner lors de vos aventures.</p>
                <p>Chez Location'Express, nous mettons un point d'honneur à offrir un service client exceptionnel. Notre équipe amicale et professionnelle est là pour vous guider à chaque étape du processus de location. Nous nous engageons à rendre votre expérience aussi fluide que possible, en vous offrant la flexibilité nécessaire pour répondre à vos besoins spécifiques.</p>
                <p>Explorez notre site pour découvrir notre gamme de véhicules, nos tarifs compétitifs et nos offres spéciales. Réservez en ligne en quelques clics et profitez d'un processus de réservation simple et sécurisé. Nous nous occupons du reste afin que vous puissiez vous concentrer sur votre voyage en toute sérénité.</p>
                <p>Lorsque vous choisissez Location'Express, vous choisissez la tranquillité d'esprit, la qualité et l'excellence. Faites-nous confiance pour rendre votre expérience de location de voiture inoubliable.</p>
                <p>Bienvenue chez Location'Express - Où votre voyage commence avec assurance !</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
          </div>
        </div>
      </div>
    </div>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    @RenderSection("JQueryValidationScripts", required: false)
    @RenderSection("ScriptAPI", required: false)
    @RenderSection("Scripts", required:false)
</body>
</html>