LocationVoiturePhilippeB/Models/Voiture.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography;

namespace LocationVoiturePhilippeB.Models
{
    /// <summary>
    /// Classe voiture avec tous ses attributs
    /// </summary>
    public class Voiture
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Marque ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Le nom de la marque doit avoir entre 2 et 50 caractères.")]
        public string Marque { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Modèle ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Le modèle de la voiture doit avoir entre 2 et 50 caractères!")]
        public string Modele { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Couleur ")]
        [CouleurValideCustom]
        public string Couleur { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Année de fabrication")]
        [Remote("ValiderAnneeFabrication", "Validation", HttpMethod = "POST")]
        public int AnneeFabrication { get; set; }
        public int? ClientId { get; set; }
        public Client? client { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Capacité maximale")]
        [Range(1,9,ErrorMessage = "La capacité de passagers maximale ne peut pas dépasser 9 personnes.")]
        public int CapaciteMax { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Image ")]
        public IFormFile? Image { get; set; }
        public string? UrlImage { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Nombre de fois louée")]
        public int NombreFoisLocation { get; set; }
        [Required(ErrorMessage = "Le champ {0} est requis")]
        [DisplayName("Prix par heure ")]
        [Range(0, 100, ErrorMessage = "Le prix par heure doit être compris entre 0 et 100.")]
        public decimal PrixParHeure { get; set; }

    }
}

LocationVoiturePhilippeB/Controllers/FichierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Controlleur qui permet l'utilisation de fichier en dehors du root
    /// - Code tiré d'une démo de Dalicia Bouallouche
    /// </summary>
    public class FichierController : Controller
    {
        private IWebHostEnvironment _hostingEnvironment;

        /// <summary>
        /// Constructeur du contrôleur de fichiers.
        /// </summary>
        /// <param name="hostingEnvironment">Service IWebHostEnvironment qui 
        ///         donne accès aux informations sur l'environnement d'hébergement 
        ///         de l'application.</param>
        public FichierController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        /// <summary>
        /// Méthode d'action qui permet de lire un fichier en dehors de wwwroot.
        /// Utilisée dans des vues qui affichent des images téléversées et 
        /// stockées en dehors de wwwroot.
        /// </summary>
        /// <param name="nomImage">Le nom de l'image</param>
        /// <param name="cheminDossier"></param>
        /// <returns></returns>
        public FileResult GetImage(string cheminImage)
        {
            if (cheminImage != null)
            {
                cheminImage = Path.Combine(_hostingEnvironment.ContentRootPath, cheminImage);

                var fileStream = new FileStream(cheminImage, FileMode.Open, FileAccess.Read);

                return File(fileStream, "images/jpg");
            }
            else { return null; }
        }
    }
}

LocationVoiturePhilippeB/Controllers/PanierController.cs
using LocationVoiturePhilippeB.Models;
using LocationVoiturePhilippeB.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Contrôlleur qui permet la gestion complète du panier de locations
    /// </summary>
    [Authorize(Roles = "Admin, Client")]
    public class PanierController : Controller
    {
        private readonly IPanierRepository _panierRepository;
        private readonly IVoitureRepository _voitureRepository;
        private IHttpContextAccessor _contextAccessor;

        /// <summary>
        /// Constructeur du controlleur pour créer une session à chaque utilisation du panier
        /// </summary>
        /// <param name="panier"></param>
        /// <param name="voiture"></param>
        /// <param name="contextAccessor"></param>
        public PanierController(IPanierRepository panier, IVoitureRepository voiture, IHttpContextAccessor contextAccessor)
        {
            _panierRepository = panier;
            _voitureRepository = voiture;
            _contextAccessor = contextAccessor;

            var panierSessionId = _contextAccessor.HttpContext.Session.GetString("PanierSessionId");
            if (string.IsNullOrEmpty(panierSessionId))
            {
                panierSessionId = Guid.NewGuid().ToString();
                _contextAccessor.HttpContext.Session.SetString("PanierSessionId", panierSessionId);
            }
            _panierRepository.SetSessionId(panierSessionId);
            ViewBag.PanierSessionId = panierSessionId;
        }
        /// <summary>
        /// Affichage du panier d'achat dans le ViewModel attribué
        /// - Le montant total est calculé avec une requête LINQ du PanierRepository
        /// </summary>
        /// <returns></returns>
        public ViewResult AfficherPanier()
        {
            PanierViewModel model = new PanierViewModel
            {
                ListeVoituresPanier = _panierRepository.VoiturePanier,
                MontantTotal = _panierRepository.MontantTotalPanier()
            };
            return View(model);
        }
        /// <summary>
        /// Méthode d'action qui permet l'ajout d'une voiture dans le panier
        /// - Appelle de la fonction "AjouterAuPanier" du PanierRepository
        /// </summary>
        /// <param name="vehiculeId"> Récupérer automatiquement quand l'utilisateur appuie sur "Ajouter au panier" dans la vue </param>
        /// <returns></returns>
        public RedirectToActionResult AjouterAuPanier(int vehiculeId)
        {
            Voiture voiture = _voitureRepository.GetVoitureById(vehiculeId);

            _panierRepository.AjouterAuPanier(voiture);

            return RedirectToAction(nameof(AfficherPanier));
        }
        /// <summary>
        /// Méthode d'action qui permet la suppression d'une voiture dans le panier
        /// - Appelle de la fonction "SupprimerDuPanier" du PanierRepository
        /// </summary>
        /// <param name="vehiculeId"></param>
        /// <returns></returns>
        public RedirectToActionResult SupprimerDuPanier(int vehiculeId)
        {
            Voiture voiture = _voitureRepository.GetVoitureById(vehiculeId);

            _panierRepository.SupprimerDuPanier(voiture);

            return RedirectToAction(nameof(AfficherPanier));
        }
        /// <summary>
        /// Méthode d'action qui supprime l'entièreté du contenu du panier
        /// </summary>
        /// <returns></returns>
        public RedirectToActionResult ViderPanier()
        {
            _panierRepository.ViderPanier();

            return RedirectToAction(nameof(AfficherPanier));
        }
    }
}

LocationVoiturePhilippeB/Controllers/VoitureController.cs
using LocationVoiturePhilippeB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LocationVoiturePhilippeB.Controllers
{
    /// <summary>
    /// Controlleur qui permet la gestion complète des voitures 
    /// </summary>
    [Authorize(Roles = "Admin, Client")]
    public class VoitureController : Controller
    {
        private IVoitureRepository _voitureRepository;
        private IWebHostEnvironment _webHostEnvironment;

        public VoitureController(IVoitureRepository voitureRepository, IWebHostEnvironment webHostEnvironment)
        {
            _voitureRepository = voitureRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        /// <summary>
        /// Affichage de la liste des voitures disponibles
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin, Client")]
        public ViewResult ListeVoitures()
        {
            return View(_voitureRepository.ListeVoitures);
        }
        /// <summary>
        /// Affichage de la vue d'ajout d'une voiture
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Ajouter()
        {
            return View();
        }
        /// <summary>
        /// Affichage de la vue de modification d'une voiture
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Modifier(int id)
        {
            Voiture voiture = _voitureRepository.GetVoitureById(id);
            return View(voiture);
        }
        /// <summary>
        /// Méthode d'action qui permet la suppression d'une voiture dans la base de données
        /// </summary>
        /// <param name="id"> Récupérer automatiquement quand on sélectionne la voiture à supprimer</param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult Supprimer(int id)
        {
            _voitureRepository.Supprimer(id);
            return RedirectToAction(nameof(ListeVoitures));
        }
        /// <summary>
        /// Méthode d'action qui permet l'ajout d'une voiture dans la BD
        /// - Redirection vers la vue des voitures (ListeVoitures)
        /// - Le code de téléversement sécuritaire est pris d'une démo de Dalicia Bouallouche
        /// - Utilisation de la validation côté serveur 
        /// </summary>
        /// <param name="voiture"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public RedirectToActionResult AjouterVoiture(Voiture voiture)
        {
            if (voiture.Image != null)
            {
                string nomImage = Path.GetFileName(voiture.Image.FileName);
                string extensionImage = Path.GetExtension(nomImage);

                var repertoireTeleversements = Path.Combine(_webHostEnvironment.ContentRootPath, "Televersements\\Voitures");

                Directory.CreateDirectory(repertoireTeleversements);

                nomImage = Guid.NewGuid().ToString() + extensionImage;

                var cheminImage = Path.Combine(repertoireTeleversements, nomImage);
                voiture.UrlImage = cheminImage;


                // Enregistrer l'image sur le disque
                using (var stream = new FileStream(cheminImage, FileMode.Create))
                {
                    voiture.Image.CopyTo(stream);
                }
            }
            if (ModelState.IsValid)
            {
                _voitureRepository.Ajouter(voiture);
                return RedirectToAction(nameof(ListeVoitures));
            }
            return RedirectToAction(nameof(Ajouter));
        }
        /// <summary>
        /// Méthode d'action qui permet la modification d'une voiture dans la BD
        /// - Redirection vers la vue des voitures (ListeVoitures)
        /// - Le code de téléversement sécuritaire est pris d'une démo de Dalicia Bouallouche
        /// - Utilisation de la validation côté serveur 
        /// </summary>
        /// <param name="voiture"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public RedirectToActionResult ModifierVoiture(Voiture voiture)
        {
            if (voiture.Image != null)
            {
                string nomImage = Path.GetFileName(voiture.Image.FileName);
                string extensionImage = Path.GetExtension(nomImage);

                var repertoireTeleversements = Path.Combine(_webHostEnvironment.ContentRootPath, "Televersements\\Voitures");

                Directory.CreateDirectory(repertoireTeleversements);

                nomImage = Guid.NewGuid().ToString() + extensionImage;

                var cheminImage = Path.Combine(repertoireTeleversements, nomImage);
                voiture.UrlImage = cheminImage;


                // Enregistrer l'image sur le disque
                using (var stream = new FileStream(cheminImage, FileMode.Create))
                {
                    voiture.Image.CopyTo(stream);
                }
            }
            if (ModelState.IsValid) 
            {
                _voitureRepository.Modifier(voiture);
                return RedirectToAction(nameof(ListeVoitures));
            }
            return RedirectToAction(nameof(Modifier));
        }
    }
}

LocationVoiturePhilippeB/Views/Voiture/Ajouter.cshtml
@model Voiture
@section JQueryValidationScripts {
    <partial name="_ValidationScriptsPartial" />
  }

<script src="~/jquery/jquery.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@{
    ViewData["Titre"] = "Ajouter une voiture";
}

<div class="container">
    <h1 class="text-center">@ViewData["Titre"]</h1>
    <form asp-controller="Voiture" asp-action="AjouterVoiture" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Marque">Marque :</label>
                    <input asp-for="Marque" type="text" class="form-control" placeholder="Entrez la marque de la voiture">
                    <span asp-validation-for="Marque" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Modele">Modèle :</label>
                    <input asp-for="Modele" type="text" class="form-control" placeholder="Entrez le modèle de la voiture">
                    <span asp-validation-for="Modele" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Couleur">Couleur :</label>
                    <input asp-for="Couleur" type="text" class="form-control" placeholder="Entrez la couleur de la voiture">
                    <span asp-validation-for="Couleur" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AnneeFabrication">Année de fabrication :</label>
                    <input asp-for="AnneeFabrication" type="number" class="form-control" placeholder="Entrez l'année de fabrication de la voiture">
                    <span asp-validation-for="AnneeFabrication" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CapaciteMax">Capacité maximale :</label>
                    <input asp-for="CapaciteMax" type="number" class="form-control" placeholder="Entrez la capacité maximale de la voiture">
                    <span asp-validation-for="CapaciteMax" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="Image">Image :</label>
                    <input asp-for="Image" type="file" class="form-control-file">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NombreFoisLocation">Nombre de fois louée :</label>
                    <input asp-for="NombreFoisLocation" value="0" type="number" class="form-control" disabled>
                    <span asp-validation-for="NombreFoisLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PrixParHeure">Prix par heure :</label>
                    <input asp-for="PrixParHeure" type="number" step="1" class="form-control" placeholder="Entrez le prix par heure de location de la voiture">
                    <span asp-validation-for="PrixParHeure" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="text-center mt-4">
            <button type="submit" class="btn btn-outline-primary">Ajouter</button>
        </div>
    </form>
</div>

LocationVoiturePhilippeB/Views/Voiture/ListeVoitures.cshtml
@model List<Voiture>

@{
    ViewData["Titre"] = "Liste des véhicules disponibles";
}

<div class="container" style="max-height: 80vh; overflow-y: auto;">
    <div class="text-center">
        <h1 class="display-4">@ViewData["Titre"]</h1>
        @if (User.IsInRole("Admin"))
        {
            <a asp-controller="Voiture" asp-action="Ajouter" class="btn btn-primary mt-3">Ajouter une voiture</a>
        }
    </div>

    <div class="row">
        @foreach (var voiture in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="@Url.Action("GetImage", "Fichier", new { cheminImage = voiture.UrlImage })" class="card-img-top" alt="Photo du véhicule">
                    <div class="card-body">
                        <h5 class="card-title">@voiture.Marque @voiture.Modele</h5>
                        <p class="card-text">Couleur: @voiture.Couleur</p>
                        <p class="card-text">Année de fabrication: @voiture.AnneeFabrication</p>
                        <p class="card-text">Capacité max: @voiture.CapaciteMax</p>
                        <hr>
                        <div>
                            <a class="btn btn-outline-success card text-center" data-toggle="modal" data-target="#modalInfosCompletes_@voiture.Id">Informations complètes</a>
                            @if (User.IsInRole("Admin"))
                            {
                                <div class="d-flex justify-content-center">
                                    <a class="btn btn-outline-danger mt-3 card text-center" data-toggle="modal" data-target="#modalSupprimer_@voiture.Id">Supprimer</a>
                                    <a class="btn btn-outline-warning mt-3 card text-center" asp-controller="Voiture" asp-action="Modifier" asp-route-id="@voiture.Id">Modifier</a>
                                </div>
                            }
                            @if (User.IsInRole("Client"))
                            {
                                <div class="d-flex justify-content-center">
                                    <a asp-controller="Panier" asp-action="AjouterAuPanier" asp-route-vehiculeId="@voiture.Id" type="button" class="btn btn-outline-info mt-3 card text-center">Ajouter au panier</a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal de confirmation de suppression -->
            <div class="modal fade" id="modalSupprimer_@voiture.Id" tabindex="-1" aria-labelledby="modalSupprimerLabel_@voiture.Id" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalSupprimerLabel_@voiture.Id">Confirmation de suppression</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Êtes-vous sûr de vouloir supprimer ce véhicule ?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                            <a class="btn btn-danger" asp-controller="Voiture" asp-action="Supprimer" asp-route-id="@voiture.Id">Confirmer</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    @foreach (var voiture in Model)
    {
        <div class="modal fade" id="modalInfosCompletes_@voiture.Id" tabindex="-1" aria-labelledby="modalInfosCompletesLabel_@voiture.Id" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalInfosCompletesLabel_@voiture.Id">Informations complètes de la voiture</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6">
                                <img src="@Url.Action("GetImage", "Fichier", new { cheminImage = voiture.UrlImage })" class="card-img-top" alt="Photo du client">
                            </div>
                            <div class="col-md-6">
                                <p><strong>Marque :</strong> @voiture.Marque</p>
                                <p><strong>Modèle :</strong> @voiture.Modele</p>
                                <p><strong>Couleur :</strong> @voiture.Couleur</p>
                                <p><strong>Année de fabrication :</strong> @voiture.AnneeFabrication</p>
                                <p><strong>Capacité passagés :</strong> @voiture.CapaciteMax</p>
                                <p><strong>Nombre de location :</strong> @voiture.NombreFoisLocation</p>
                                <p><strong>Prix par heure :</strong> @voiture.PrixParHeure $</p>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

LocationVoiturePhilippeB/Views/Voiture/Modifier.cshtml
@model Voiture
@section JQueryValidationScripts {
    <partial name="_ValidationScriptsPartial" />
  }
<script src="~/jquery/jquery.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@{
    ViewData["Titre"] = "Modifier une voiture";
}

<div class="container">
    <h1 class="text-center">@ViewData["Titre"]</h1>

    <form asp-controller="Voiture" asp-action="ModifierVoiture" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input asp-for="Id" type="hidden" class="form-control" required>
                </div>
                <div class="form-group">
                    <label asp-for="Marque">Marque :</label>
                    <input asp-for="Marque" type="text" class="form-control" placeholder="Entrez la marque de la voiture">
                    <span asp-validation-for="Marque" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Modele">Modèle :</label>
                    <input asp-for="Modele" type="text" class="form-control" placeholder="Entrez le modèle de la voiture">
                    <span asp-validation-for="Modele" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Couleur">Couleur :</label>
                    <input asp-for="Couleur" type="text" class="form-control" placeholder="Entrez la couleur de la voiture">
                    <span asp-validation-for="Couleur" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AnneeFabrication">Année de fabrication :</label>
                    <input asp-for="AnneeFabrication" type="number" class="form-control" placeholder="Entrez l'année de fabrication de la voiture">
                    <span asp-validation-for="AnneeFabrication" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CapaciteMax">Capacité maximale :</label>
                    <input asp-for="CapaciteMax" type="number" class="form-control" placeholder="Entrez la capacité maximale de la voiture">
                    <span asp-validation-for="CapaciteMax" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="Image">Image :</label>
                    <input asp-for="Image" type="file" class="form-control-file">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NombreFoisLocation">Nombre de fois louée :</label>
                    <input asp-for="NombreFoisLocation" value="0" type="number" class="form-control">
                    <span asp-validation-for="NombreFoisLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PrixParHeure">Prix par heure :</label>
                    <input asp-for="PrixParHeure" type="number" step="1" class="form-control" placeholder="Entrez le prix par heure de location de la voiture">
                    <span asp-validation-for="PrixParHeure" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-outline-warning mt-4">Modifier</button>
        </div>
    </form>
</div>